## 配置数据库驱动
#  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#  # 配置数据库url
#  spring.datasource.url=jdbc:mysql://127.0.0.1:3306/skymall_sms?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#  # 配置数据库用户名
#  spring.datasource.username=root
#  # 配置数据库密码
#  spring.datasource.password=root
#spring:
#  datasource:
#    data-username: root
#    data-password: root
#    url: jdbc:mysql://127.0.0.1:3306/skymall_oms?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
server:
  port: 11000


spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  application:
    name: skymall-ware
